
tasks:
  - name: SporosDAO App
    init: |
      # bring in secret access tokens from gitpod user dashboard
      eval $(gp env -e)
      # builds the images from the dockerfiles
      docker-compose build
      gp sync-done build
    command: |
      # update install deps
      docker-compose -f docker-compose.yaml -f docker-compose.install.yaml --profile install up --no-deps
      # start app modules
      docker-compose up -d
      # set API path
      gp await-port 3001 && \
      gp env REACT_APP_SWEAT_TOKEN_API_BASEPATH=$(gp url 3001)

vscode:
  extensions:
    - ms-vscode.vscode-typescript-tslint-plugin
    - bungcip.better-toml

    - esbenp.prettier-vscode

ports:

  - port: 3000-8999
    onOpen: ignore

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod
