version: "3.9"

networks:
  sweat-token:
    name: sweat-token

services:
  contracts:
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    image: sweat-token/dev
    networks:
      - sweat-token
    volumes:
      - ./contracts:/app/contracts
  backend:
    ports:
      - 3001:3001
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    image: sweat-token/dev
    networks:
      - sweat-token
    environment:
      - DATA_DIR=/data
      - LOG_LEVEL=info
    volumes:
      - ./backend:/app/backend
  frontend:
    ports:
      - 3000:3000
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    image: sweat-token/dev
    networks:
      - sweat-token
    environment:
      - DATA_DIR=/data
      - LOG_LEVEL=info
    volumes:
      - ./frontend:/app/frontend
  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./data/mongodb:/data/db
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/